#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

define('BASE_PATH', __DIR__);

use App\Core\Migration;

$command = $argv[1] ?? null;

switch ($command) {

    case 'migrate':

        $migration = new Migration();

        $migration->run();

        break;

    default:

        echo "Comando não encontrado\n";

}